# Site settings
title: Sporadic Analytics 
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Short projects as I carry on my learnings and playings in R, Python, JS etc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://philmassie.github.io" # the base hostname & protocol for your site
twitter_username: philmassie
github_username:  philmassie

# Build settings
markdown: kramdown
