<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Plot a wind rose in R</title>
  <meta property="og:title" content="Plot a wind rose in R" />
  <meta name="twitter:title" content="Plot a wind rose in R" />
  <meta name="description" content="Introduction This is another post regarding some plots that I needed to make for a publication. As before, I relied heavily on Stack Exchange and many other sites for figuring out how to get my plot looking the way I needed it to, and so this is my attempt to contribute back to the broader community.
In my article I wanted a graphic which illustrated the preferred outward post-moult migration direction of adult female southern elephant seals from Marion Island.">
  <meta property="og:description" content="Introduction This is another post regarding some plots that I needed to make for a publication. As before, I relied heavily on Stack Exchange and many other sites for figuring out how to get my plot looking the way I needed it to, and so this is my attempt to contribute back to the broader community.
In my article I wanted a graphic which illustrated the preferred outward post-moult migration direction of adult female southern elephant seals from Marion Island.">
  <meta name="twitter:description" content="Introduction This is another post regarding some plots that I needed to make for a publication. As before, I relied heavily on Stack Exchange and many other sites for figuring out how to get my plot …">
  <meta name="author" content="Philip Massie"/>
  <link href='https://philmassie.github.io/img/favicon.ico' rel='icon' type='image/x-icon'/>
  <meta property="og:image" content="https://philmassie.github.io/img/mug.png" />
  <meta name="twitter:image" content="https://philmassie.github.io/img/mug.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@philmassie" />
  <meta name="twitter:creator" content="@philmassie" />
  <meta property="og:url" content="https://philmassie.github.io/post/20160630/ggplot2_wind_rose/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="kabelsalat" />

  <meta name="generator" content="Hugo 0.31" />
  <link rel="canonical" href="https://philmassie.github.io/post/20160630/ggplot2_wind_rose/" />
  <link rel="alternate" href="" type="application/rss+xml" title="kabelsalat">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://philmassie.github.io/css/main.css" /><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/highlighting.css" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/pygment_highlights.css" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/highlight.min.css" />


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" integrity="sha256-sCl5PUOGMLfFYctzDW3MtRib0ctyUvI9Qsmq2wXOeBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" integrity="sha256-BFeI1V+Vh1Rk37wswuOYn5lsTcaU96hGaI7OUVCLjPc=" crossorigin="anonymous" />



<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

<div class="pswp__bg"></div>

<div class="pswp__scroll-wrap">
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    <div class="pswp__ui pswp__ui--hidden">
    <div class="pswp__top-bar">
      
      <div class="pswp__counter"></div>
      <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
      <button class="pswp__button pswp__button--share" title="Share"></button>
      <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
      <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
      
      
      <div class="pswp__preloader">
        <div class="pswp__preloader__icn">
          <div class="pswp__preloader__cut">
            <div class="pswp__preloader__donut"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
      <div class="pswp__share-tooltip"></div>
    </div>
    <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
    </button>
    <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
    </button>
    <div class="pswp__caption">
      <div class="pswp__caption__center"></div>
    </div>
    </div>
    </div>
</div>

<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-24074009-11', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://philmassie.github.io/">kabelsalat</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="Blog" href="/">Blog</a>
            </li>
          
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="/tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
          <a title="kabelsalat" href="https://philmassie.github.io/">
            <img class="avatar-img" src="https://philmassie.github.io/img/mug.png" alt="kabelsalat" />
          </a>
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>Plot a wind rose in R</h1>
                
                
                  <span class="post-meta">
  <i class="fa fa-calendar-o"></i>&nbsp;Posted on June 30, 2016
  &nbsp;|&nbsp; <i class="fa fa-clock-o"></i> 4 min (830 mots)
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        

<h2 id="introduction">Introduction</h2>

<p>This is another post regarding some plots that I needed to make for a publication. As before, I relied heavily on Stack Exchange and many other sites for figuring out how to get my plot looking the way I needed it to, and so this is my attempt to contribute back to the broader community.</p>

<p>In my article I wanted a graphic which illustrated the preferred outward post-moult migration direction of adult female southern elephant seals from Marion Island. In reality it doesn&rsquo;t matter too much what you want to plot, and these sorts of plots are more generally used for wind direction illustrations. Really, they are like radial histograms. In fact, if you look through the ggplot2 call, it is basically a histogram until the last couple of lines, where it is wrapped into a wind rose.</p>

<h2 id="the-data">The data</h2>

<p>As I mentioned, my data was related to seal swimming directions, gathered from satellite tags. For this tutorial I will simulate 100000 directions using the wrapped normal function (rwrpnorm) from the CircStats package.</p>

<pre><code class="language-r">library(ggplot2)
library(CircStats)

set.seed(1)
data &lt;- data.frame(direction = deg(rwrpnorm(100000, rad(225), rho=0.8, sd=1)))

# Take a quick look...
hist(data$direction, main = &quot;Histogram of hypothetical direction frequencies.&quot;, xlab = &quot;Direction&quot;, ylab = &quot;Frequency&quot;)
</code></pre>

<p><img src="histo-1.png" alt="" /><!-- --></p>

<p>That looks like a reasonable distribution of directions, favouring 225°.</p>

<h2 id="method">Method</h2>

<p>There are various ways to split and plot these data. Some searching lead me <a href="http://stackoverflow.com/questions/17266780/wind-rose-with-ggplot-r">to this one</a>. First we will define the bin width (30°), then we will define dir.breaks which stores the range of each bin as follows 345°-15°, 15°-45°, 45°-75° etc.</p>

<pre><code class="language-r"># choose bin size (degrees/bin)
deg &lt;- 30 
# define the range of each bin
dir.breaks &lt;- seq(0-(deg/2), 360+(deg/2), deg)
</code></pre>

<p>Now we generate a factor variable, exchanging the directions with the ranges. We&rsquo;ll also generate some pretty labels and assign them as levels of the new object. Finally we&rsquo;ll attach the new variable to the main dataset.</p>

<pre><code class="language-r"># assign each direction to a bin range
dir.binned &lt;- cut(data$direction,
                       breaks = dir.breaks,
                       ordered_result = TRUE)
# generate pretty lables
dir.labels &lt;- as.character(c(seq(0, 360-deg, by = deg), 0))
# replace ranges with pretty bin lables
levels(dir.binned) &lt;- dir.labels
# Assign bin names to the original data set
data$dir.binned &lt;- dir.binned
</code></pre>

<h2 id="plotting">Plotting</h2>

<h3 id="theming">Theming</h3>

<p>The important points here are blank values for <code>panel.border</code> and <code>panel.grid</code>. This turns off the default background for ggplot2 so that we can define the borders and grids manually later.</p>

<pre><code class="language-r">thm &lt;- theme_bw() + 
    theme(axis.text.x = element_text(size=8, face = &quot;plain&quot;),
          axis.text.y = element_text(size=8, face = &quot;plain&quot;),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size=8, face = &quot;plain&quot;, hjust = 0.9, vjust = 1.3),
          panel.border = element_blank(),
          panel.grid  = element_blank())
</code></pre>

<h3 id="now-the-main-plot">Now the main plot&hellip;</h3>

<p>The main plot sets things up quite specifically. What we need to know before going on is the frequency of the most common bin.</p>

<pre><code class="language-r">summary(dir.binned)
</code></pre>

<pre><code>##     0    30    60    90   120   150   180   210   240   270   300   330 
##    79     1     5    83   884  4993 15875 28134 28403 15751  4926   866
</code></pre>

<p>So there are 28403 counts of the 240° bin. We need this value to set our y-scales correctly. Our y-axis will have breaks every 5000 counts so we&rsquo;ll use 30000 as the max for the y-axis. The first parts of this plot will plot a rectangular histogram, only the <code>coord_polar</code> function wraps it into a wind rose.</p>

<pre><code class="language-r"># initialise the plot
plt.dirrose &lt;- ggplot() +
    # since the plot background is blank we'll add a series of horizontal lines, at 5000 count intervals, up to 25000.
    geom_hline(yintercept = seq(0, 25000, by = 5000), colour = &quot;grey60&quot;, size = 0.3) +
    # Now we add a darker horizontal line as the top border at 30000.
    geom_hline(yintercept = 30000, colour = &quot;black&quot;, size = 0.3) +
    # We want 12 vertical lines representing the centers of the 30° ranges.
    geom_vline(xintercept = c(seq(1,12,1)), colour = &quot;grey60&quot;, size = 0.3) +
    # On top of everything we place the histogram bars.
    geom_bar(data = data, aes(x = dir.binned), width = 1, colour=&quot;black&quot;, size = 0.3, alpha=0.5) + 
    # Add the x-axis labels
    scale_x_discrete( drop = FALSE, labels = c(0, &quot;&quot;, &quot;&quot;, 90, &quot;&quot;, &quot;&quot;, 180, &quot;&quot;, &quot;&quot;, 270, &quot;&quot;, &quot;&quot;)) +
    # Add the y-axis labels
    scale_y_continuous(limits = c(0, 30000), expand = c(0, 0), 
                       breaks = c(0, 5000, 10000, 15000, 20000, 25000, 30000), 
                       labels = c(0, 5, 10, 15, 20, 25, 30)) +
    # Add the axis titles
    labs(x = 'Outward step bearing (°)', y = 'Count of outward steps (x10³)') +
    # If you only use the plot code up till here you will get a histogram.
    # the next line wraps the histogram into a windrose
    coord_polar(start = -(deg/2)*(pi/180)) +
    # apply theme
    thm

plt.dirrose
</code></pre>

<p><img src="rose-1.png" alt="" /><!-- --></p>

<p>There we have it; a wind rose, in grey scale illustrating our data exactly as we need it to.</p>

<p><strong><em>Saving the plot according to the publishers requirements</em></strong></p>

<p>For completeness, this is one approach to saving your plots</p>

<pre><code class="language-r">ggsave(filename = 'plt.dirrose.png', plot = plt.dirrose, width = 84, height = 84, units=&quot;mm&quot;, dpi = 300, type=&quot;cairo-png&quot;)
</code></pre>

<p>Hope this helps :)</p>

      </article>

      <ul class="pager blog-pager">
        
          <li class="previous">
            <a href="https://philmassie.github.io/post/20160622/ggplot2_contours/" data-toggle="tooltip" data-placement="top" title="Plotting greyscale contoured data in R with ggplot2">&larr; Previous Post</a>
          </li>
        
        
          <li class="next">
            <a href="https://philmassie.github.io/post/20160714/election_effort/" data-toggle="tooltip" data-placement="top" title="South African municipal elections 2016">Next Post &rarr;</a>
          </li>
        
      </ul>


      
        
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:philmassie@webafrica.org.za" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/philmassie" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/philmassie" title="Twitter">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/philmassie" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.instagram.com/philmassie" title="Instagram">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          
            
              <a href="philmassie.github.io">Philip Massie</a>
            
          

          &nbsp;&bull;&nbsp;
          2017

          
            &nbsp;&bull;&nbsp;
            <a href="https://philmassie.github.io/">kabelsalat</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.31</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://philmassie.github.io/js/main.js"></script>
<script src="https://philmassie.github.io/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script><script> renderMathInElement(document.body); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js" integrity="sha256-UplRCs9v4KXVJvVY+p+RSo5Q4ilAUXh7kpjyIP5odyc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js" integrity="sha256-PWHOlUzc96pMc8ThwRIXPn8yH4NOLu42RQ0b9SpnpFk=" crossorigin="anonymous"></script>
<script src="https://philmassie.github.io/js/load-photoswipe.js"></script>



  </body>
</html>

