<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Plotting greyscale contoured data in R with ggplot2</title>
  <meta property="og:title" content="Plotting greyscale contoured data in R with ggplot2" />
  <meta name="twitter:title" content="Plotting greyscale contoured data in R with ggplot2" />
  <meta name="description" content="Introduction Preparing figures for publication can take a long time (well it does for me anyway), and I relied very heavily on numerous online resources to figure out some of the dos and don&rsquo;ts. Obviously I owe massive thanks to the hundreds of blogs and Stack Exchange questions and answers I relied on. Where I can, I will try to link to them.
Additionally, this tutorial covers a little bit about working with reshaped gridded data, shape files, GeoTIFF data and even a simple homemade polygon.">
  <meta property="og:description" content="Introduction Preparing figures for publication can take a long time (well it does for me anyway), and I relied very heavily on numerous online resources to figure out some of the dos and don&rsquo;ts. Obviously I owe massive thanks to the hundreds of blogs and Stack Exchange questions and answers I relied on. Where I can, I will try to link to them.
Additionally, this tutorial covers a little bit about working with reshaped gridded data, shape files, GeoTIFF data and even a simple homemade polygon.">
  <meta name="twitter:description" content="Introduction Preparing figures for publication can take a long time (well it does for me anyway), and I relied very heavily on numerous online resources to figure out some of the dos and don&rsquo;ts. …">
  <meta name="author" content="Philip Massie"/>
  <link href='https://philmassie.github.io/img/favicon.ico' rel='icon' type='image/x-icon'/>
  <meta property="og:image" content="https://philmassie.github.io/img/mug.png" />
  <meta name="twitter:image" content="https://philmassie.github.io/img/mug.png" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@philmassie" />
  <meta name="twitter:creator" content="@philmassie" />
  <meta property="og:url" content="https://philmassie.github.io/post/20160622/ggplot2_contours/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="kabelsalat" />

  <meta name="generator" content="Hugo 0.31" />
  <link rel="canonical" href="https://philmassie.github.io/post/20160622/ggplot2_contours/" />
  <link rel="alternate" href="" type="application/rss+xml" title="kabelsalat">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://philmassie.github.io/css/main.css" /><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/highlighting.css" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/pygment_highlights.css" />
  <link rel="stylesheet" href="https://philmassie.github.io/css/highlight.min.css" />


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" integrity="sha256-sCl5PUOGMLfFYctzDW3MtRib0ctyUvI9Qsmq2wXOeBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" integrity="sha256-BFeI1V+Vh1Rk37wswuOYn5lsTcaU96hGaI7OUVCLjPc=" crossorigin="anonymous" />



<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

<div class="pswp__bg"></div>

<div class="pswp__scroll-wrap">
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    <div class="pswp__ui pswp__ui--hidden">
    <div class="pswp__top-bar">
      
      <div class="pswp__counter"></div>
      <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
      <button class="pswp__button pswp__button--share" title="Share"></button>
      <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
      <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
      
      
      <div class="pswp__preloader">
        <div class="pswp__preloader__icn">
          <div class="pswp__preloader__cut">
            <div class="pswp__preloader__donut"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
      <div class="pswp__share-tooltip"></div>
    </div>
    <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
    </button>
    <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
    </button>
    <div class="pswp__caption">
      <div class="pswp__caption__center"></div>
    </div>
    </div>
    </div>
</div>

<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-24074009-11', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://philmassie.github.io/">kabelsalat</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="Blog" href="/">Blog</a>
            </li>
          
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="/tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
          <a title="kabelsalat" href="https://philmassie.github.io/">
            <img class="avatar-img" src="https://philmassie.github.io/img/mug.png" alt="kabelsalat" />
          </a>
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>Plotting greyscale contoured data in R with ggplot2</h1>
                
                
                  <span class="post-meta">
  <i class="fa fa-calendar-o"></i>&nbsp;Posted on June 22, 2016
  &nbsp;|&nbsp; <i class="fa fa-clock-o"></i> 10 min (2023 mots)
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        

<h3 id="introduction">Introduction</h3>

<p>Preparing figures for publication can take a long time (well it does for me anyway), and I relied very heavily on numerous online resources to figure out some of the dos and don&rsquo;ts. Obviously I owe massive thanks to the hundreds of blogs and Stack Exchange questions and answers I relied on. Where I can, I will try to link to them.</p>

<p>Additionally, this tutorial covers a little bit about working with reshaped gridded data, shape files, GeoTIFF data and even a simple homemade polygon. This then is my contribution to folks trying to get their plots to look the way they need them to.</p>

<p>As most people know, publishing in colour is way more expensive than in grey scale. The costs were completely prohibitive for myself and my co-authors, so I made efforts to change my beautiful, spectacularly coloured plots, which looked so nice in slide shows, into grey scale.</p>

<p>This is also my first attempt to use R Markdown in a real-world scenario. Please feel free to provide critical feedback.</p>

<h3 id="the-data">The data</h3>

<p>This plot is showing mean values of the derived variable eddy kinetic (EKE) energy to the south west of Marion Island (in the Southern Ocean) from 2008 to 2010. Interactions between the Antarctic Circumpolar Current and a series of undersea faults in the South West Indian Ridge, give rise to an area of instability, and it is the degree and extent of this instability that I set out to investigate via EKE.</p>

<p>EKE is derived from u and v components <a href="http://goo.gl/4c3ccI">like this</a>. The friendly folks at <a href="http://www.aviso.altimetry.fr">AVISO</a> have kindly let me use and make available this subset of their data for the purpose of this tutorial. Perhaps if someone is interested I&rsquo;ll make another post showing how I went about the calculations and wrangling.</p>

<p>If you are interested in this sort of data, please check out AVISO. They make available unfathomable amounts of absolutely beautiful data for free. All you need is an account and it&rsquo;s yours - Honestly access to data like this blows my mind. I wish it was like this with South African regional data&hellip; but that&rsquo;s another story.</p>

<h3 id="method">Method</h3>

<p>Start by loading all the necessary libraries, setting working directories and loading data. You can download the EKE data set <a href="http://www.philmassie.com/data/data.eke.rdata">here</a>.</p>

<pre><code class="language-r">library(sp)
library(rgdal)
library(raster)
library(ggplot2)
library(plyr)

load(file = &quot;data/data.eke.rdata&quot;)
head(data.eke)
</code></pre>

<pre><code>##       lon     lat          eke
## 1 -18.875 -68.625 1.052298e-04
## 2 -18.875 -68.375 1.009409e-04
## 3 -18.875 -68.125 7.404519e-05
## 4 -18.875 -67.875 6.044744e-05
## 5 -18.875 -67.625 8.102543e-05
## 6 -18.875 -67.375 9.289138e-05
</code></pre>

<pre><code class="language-r"># When we derive EKE, grid cells over land produce NaNs, so we must replace them with NAs
data.eke$eke[which(is.nan(data.eke$eke))] &lt;- NA
</code></pre>

<h4 id="define-our-map-extents">Define our map extents</h4>

<p>The EKE data spans from -18.875 E to 43.875 E and -38.88 N to -68.62 N.
Those are the extents needed for the full study, but it&rsquo;s too much for the plot, so we must subset it.</p>

<pre><code class="language-r">latmin &lt;- -55
latmax &lt;- -43
lonmin &lt;- 20
lonmax &lt;- 43
map.extents &lt;- extent(lonmin, lonmax, latmin, latmax)
data.eke.sub &lt;- subset(data.eke,
                       data.eke$lat &gt;= latmin &amp;
                           data.eke$lat &lt;= latmax &amp;
                           data.eke$lon &gt;= lonmin &amp;
                           data.eke$lon &lt;= lonmax)
</code></pre>

<h4 id="shape-files">Shape Files</h4>

<p>The plot area includes the Prince Edward Islands. Instead of leaving blank, blocky spaces, let&rsquo;s use some shape files to make it look neater. These shape files come from <a href="http://www.naturalearthdata.com">http://www.naturalearthdata.com</a>. They are from the &lsquo;fine scale (1:10), Admin 0 -Countries&rsquo; set available for free from <a href="http://www.naturalearthdata.com/downloads/10m-cultural-vectors/">here</a>.</p>

<pre><code class="language-r"># read in the shape file
countries &lt;- readOGR(&quot;shapes&quot;, layer=&quot;ne_10m_admin_0_countries&quot;)
# Add an id column to the data slot of countries, based on rownames
countries@data$id &lt;- rownames(countries@data)
# Fortify the spatial polygons for ggplot2 - likes long format data
# The resulting data frame contains all the spatial data and the id but no information labels.
countries.df &lt;- fortify(countries)
# Use the id column to join all the label data in countries@data to the new dataframe.
countries.df &lt;- join(countries.df, countries@data, by=&quot;id&quot;)
# Now we can subset the new dataframe to include only South Africa and her Islands and tidy up a bit
za &lt;- subset(countries.df, countries.df$ISO_A2==&quot;ZA&quot;)
rm(countries, countries.df)
</code></pre>

<h4 id="geotiff">GeoTIFF</h4>

<p>The plot needs some bathymetric contour lines. We will use the ETOPO1 data for this via a GeoTIFF. There are higher resolution data sets around (e.g. ETOTPO2 and GEBCO) but ETOPO1 will suffice for this application. The ETOPO1 data is (freely?) available from <a href="http://www.ngdc.noaa.gov/mgg/global/global.html">here</a>.</p>

<pre><code class="language-r"># Load up the geotiff
etopo1.full &lt;- raster(&quot;etopo/ETOPO1_Ice_c_geotiff.tif&quot;)
# Crop out our ROI
etopo.crop &lt;- crop(etopo1.full, map.extents)
# Prepare for ggplot2 (long format) and tidy up a bit
etopo.crop.df &lt;- as.data.frame(etopo.crop, xy=TRUE)
names(etopo.crop.df) &lt;- c(&quot;long&quot;, &quot;lat&quot;, &quot;z&quot;)
rm(etopo1.full)
</code></pre>

<h4 id="polygon">Polygon</h4>

<p>Lastly we&rsquo;ll build a simple polygon to demarcate an area we consider within the region of elevated EKE (eddy field).</p>

<pre><code class="language-r"># Define extents
eflatmin &lt;- -53
eflatmax &lt;- -47.33
eflonmin &lt;- 27.33
eflonmax &lt;- 37.66
# bind the data into sequential coordinates, outlining the new polygon and generate a polygon.
ef.coords &lt;- cbind(c(eflonmin, eflonmax, eflonmax, eflonmin, eflonmin),
                   c(eflatmax, eflatmax, eflatmin, eflatmin, eflatmax))
ef.poly &lt;- Polygon(ef.coords)
# Prepare for ggplot2 and tidy up
ef.df &lt;- fortify(ef.poly)
# set an individual group for plotting
ef.df$group &lt;-1
rm(ef.coords, ef.poly)
</code></pre>

<h3 id="plot-time">Plot time</h3>

<p>Finally we have all the bits in place so we can build a plot. We&rsquo;ll start with the colourful version, and then see how to refine it to a grey scale contoured version.</p>

<h4 id="preliminaries">Preliminaries</h4>

<p>We start by defining the plot label positions and text and then set some custom theme stuff. See <a href="http://docs.ggplot2.org/current/theme.html">here</a> for more on theming.</p>

<pre><code class="language-r"># define some lables and their coordinates
lbl &lt;- data.frame(x = c(40, 36, 30, 37.1, 22.5),
                  y = c(-46.5, -53.4, -50, -45, -51.5),
                  txt = c(&quot;Marion Island&quot;, &quot;Eddy Field&quot;, &quot; &quot;, &quot;SWIR&quot;, &quot;SWIR&quot;))
# Define the theme data as I like it for these plots...
thm &lt;- theme_bw() + 
    theme(axis.text.x = element_text(size=8, face = &quot;plain&quot;),
          axis.text.y = element_text(size=8, face = &quot;plain&quot;),
          axis.title.x = element_text(size=8, face = &quot;plain&quot;),
          axis.title.y = element_text(size=8, face = &quot;plain&quot;),
          axis.ticks.x = element_line(size=0.3),
          axis.ticks.y = element_line(size=0.3),          
          legend.key.height = unit(13, units=&quot;mm&quot;),
          legend.text = element_text(size=8, face = &quot;plain&quot;),
          legend.title = element_text(size=8, angle = 90, vjust = 1, face = &quot;plain&quot;),
          legend.title.align = 0.5,
          panel.border = element_rect(colour = &quot;black&quot;, fill=NA, size=.3))
</code></pre>

<h4 id="coloured-tiles-plot">Coloured tiles plot</h4>

<p>Ggplot2 is even more awesome than anything you might have read, but it can be intimidating (I find). The best I can suggest is to keep playing and you&rsquo;ll start to get a handle on. One of the biggest difficulties for me was figuring out what order the layers should be in. This is where I ended up. I&rsquo;d like to tell you that I had figured out an overriding set of rules, but there was some trial and error involved.</p>

<p>I have tried to comment the coloured plot extensively.</p>

<pre><code class="language-r"># initiate the plot
plot.eke.colour &lt;- ggplot() +
    # include a layer with the eke data as coloured tile data
    geom_tile(data=data.eke.sub, aes(x=lon,y=lat,fill=eke)) +
    # include the shape file data
    geom_polygon(data = za, aes(x = long, y = lat, group = group), 
                 colour=&quot;black&quot;, fill=&quot;white&quot;, alpha=1, size = 0.3) + 
    # include the home made polygon data
    geom_polygon(data=ef.df, aes(x=long, y=lat, group=group), 
                 colour=&quot;black&quot;, fill=&quot;white&quot;, alpha=0, linetype=&quot;dashed&quot;, size = 0.3) +
    # include the bathymetry data with geom_contour. Define a single custom break
    geom_contour(data=etopo.crop.df, aes(x=long,y=lat,z=z), 
                 breaks=c(-3000), colour=&quot;black&quot;, size = 0.3) +
    # axis lables
    labs(x = 'Longitude (ºE)', y = 'Latitude (ºN)') +
    # map projection - boring choice but suits the task at hand
    coord_map(&quot;mercator&quot;) +
    # this trims unwanted whitespace around the plot
    coord_fixed(xlim = c(lonmin, lonmax), ylim = c(latmin, latmax), expand = FALSE) +
    # change the default EKE colour to more traditional rainbow colours (oceanography etc)
    scale_fill_gradientn(colours = rev(rainbow(7, end=4/6)), 
                         space = &quot;Lab&quot;, 
                         guide = guide_colorbar(title=&quot;Eddy kinetic energy (cm²/s²)&quot;, 
                                                title.position=&quot;right&quot;)) +
    # include the lables defined earlier
    geom_text(data=lbl, aes(x=x, y=y, label=txt), size=rel(3), colour=&quot;white&quot;, fontface=&quot;bold&quot;, alpha = 1) +
    geom_text(data=lbl, aes(x=x+0.01, y=y+0.01, label=txt), size=rel(3), colour=&quot;black&quot;, fontface=&quot;bold&quot;) +
    # include the theme settings
    thm
plot.eke.colour
</code></pre>

<p><img src="coloured_plot-1.png" alt="" /><!-- --></p>

<p>That looks pretty good. Unfortunately when we save the file, things don&rsquo;t always look the same as they do on the screen so there is generally some fine tuning involved. This version, as it stands, makes rather a good print. The colour palette is familiar to all my MATLAB/Python oceanographic colleagues too.</p>

<p><strong><em>Saving the plot according to the publishers requirements</em></strong></p>

<p>For completeness, this is one approach to saving your plots</p>

<pre><code class="language-r">ggsave(filename = 'plot.eke.colour.png', plot = plot.eke.colour, width = 174, height = 105, units=&quot;mm&quot;, dpi = 300, type=&quot;cairo-png&quot;)
</code></pre>

<h4 id="greyscale-contoured-plot">Greyscale contoured plot</h4>

<p>If we just jump in and plot the existing data using the stat_contour() approach we immediately hit a problem. It&rsquo;s a little difficult to explain, but easy enough to understand if you play around a bit. I&rsquo;ll try my best.</p>

<p>Some of the contoured values exist as closed polygons within the plot frame. These plot as we would expect. Unfortunately, other contoured values are (now) polylines. These lines would have closed somewhere outside of the plot extents, but were cropped, resulting in open polygons/polylines. As a result, ggplot2 can&rsquo;t fill them with shading as required. Ggplot2 closes them automatically by joining their ends. This is pretty catastrophic. You can see what happens for yourself by exchanging <code>data.eke.sub.contour</code> for <code>data.eke.sub</code> in the plot code below.</p>

<p><strong><em>Calculate a low arbitrary value</em></strong></p>

<p>To avoid this we need to add extra, make-believe EKE data just outside the plotting frame. We set this to a low, arbitrary value which allows ggplot2 to close off the contour polygons which we are interested in. What the arbitrary value is, is not <em>that</em> important, as long as it is lower than everything else. I found this approach on <a href="http://stackoverflow.com/questions/28469829/how-to-fill-in-the-contour-fully-using-stat-contour">stackoverflow here</a>. It looks at the data spread, divides it into n bins and sets an arbitrary value according to the lowest value minus the bin width * 1.5.</p>

<pre><code class="language-r">bins &lt;- 50
bin.width &lt;- diff(range(na.omit(data.eke.sub$eke))) / bins
arbitary.value &lt;- min(na.omit(data.eke.sub$eke)) - bin.width * 1.5

# Build some data frames representing 1 degree of extra EKE data in each direction, with the arbitrary value as EKE
min &lt;- sapply(data.eke.sub, min, na.rm = TRUE)
max &lt;- sapply(data.eke.sub, max, na.rm = TRUE)

seq.lat &lt;- seq(min['lat'], max['lat'], 0.25)
seq.lon &lt;- seq(min['lon'], max['lon'], 0.25)

west.edge &lt;- data.frame(lon = rep(min['lon'] - 1, length(seq.lat)), lat = seq.lat, eke = arbitary.value)
east.edge &lt;- data.frame(lon = rep(max['lon'] + 1, length(seq.lat)), lat = seq.lat, eke = arbitary.value)
south.edge &lt;- data.frame(lon = seq.lon, lat = rep(min['lat'] - 1, length(seq.lon)), eke = arbitary.value)
north.edge &lt;- data.frame(lon = seq.lon, lat = rep(max['lat'] + 1, length(seq.lon)), eke = arbitary.value)

# rbind the new data to the existing data and tidy up
data.eke.sub.contour &lt;- rbind(data.eke.sub, west.edge, east.edge, north.edge, south.edge)

rm(bins, bin.width, arbitary.value, min, max, seq.lat, seq.lon, west.edge, east.edge, north.edge, south.edge)
</code></pre>

<p><strong><em>Now we plot</em></strong></p>

<p>Now, with our newly padded dataset, we can complete the greyscale plot. I&rsquo;ve only commented the changed lines in this plot (vs. the colour plot above).</p>

<pre><code class="language-r">plot.eke.contour.grey &lt;- ggplot() +
    # This line denotes the newly padded data, as a contour statistic.
    # ..level.. indicates that the fill aesthetic is calculated by the contour statistic.
    # breaks manually define which contours we want to keep.
    stat_contour(data = data.eke.sub.contour, aes(x = lon, y = lat, z = eke, fill = ..level..), 
                 geom = &quot;polygon&quot;, breaks = c(0, 0.02, 0.04, 0.06, 0.08)) +
    geom_polygon(data = za, aes(x = long, y = lat, group = group), 
                 colour=&quot;black&quot;, fill=&quot;white&quot;, alpha=1, size = 0.3) + 
    geom_polygon(data=ef.df, aes(x=long, y=lat, group=group), 
                 colour=&quot;black&quot;, fill=&quot;white&quot;, alpha=0, linetype=&quot;dashed&quot;, size = 0.3) +
    geom_contour(data=etopo.crop.df, aes(x=long,y=lat,z=z), breaks=c(-3000), colour=&quot;black&quot;, size = 0.3) +
    coord_map(&quot;mercator&quot;) +
    coord_fixed(xlim = c(lonmin, lonmax), ylim = c(latmin, latmax), expand = FALSE) +
    labs(x = 'Longitude (ºE)', y = 'Latitude (ºN)') +
    # Here the grey scale colours are defined for the plot and the legend
    scale_fill_gradient(low = &quot;gray25&quot;, high = &quot;gray95&quot;,
                        space = &quot;Lab&quot;, 
                        guide = guide_colorbar(title=&quot;Eddy kinetic energy (cm²/s²)&quot;, title.position=&quot;right&quot;)) +
    geom_text(data=lbl, aes(x=x, y=y, label=txt), size=rel(3), colour=&quot;white&quot;) +
    thm
plot.eke.contour.grey
</code></pre>

<p><img src="greyscale_plot-1.png" alt="" /><!-- --></p>

<p>There we go! The contours look great. There aren&rsquo;t too many of them, they don&rsquo;t have distracting borders, the 3000 m bathymetry contour looks nice and isn&rsquo;t overly distracting.</p>

<p><strong><em>Saving the plot according to the publishers requirements</em></strong></p>

<p>For completeness, this is one approach to saving your plots</p>

<pre><code class="language-r">ggsave(filename = 'plot.eke.contour.grey.png', plot = plot.eke.contour.grey, width = 174, height = 105, units=&quot;mm&quot;, dpi = 300, type=&quot;cairo-png&quot;)
</code></pre>

<p>I hope this helps someone :)</p>

      </article>

      <ul class="pager blog-pager">
        
          <li class="previous">
            <a href="https://philmassie.github.io/post/20171216/add_simple_authentication_to_rshiny/" data-toggle="tooltip" data-placement="top" title="">&larr; Previous Post</a>
          </li>
        
        
          <li class="next">
            <a href="https://philmassie.github.io/post/20160630/ggplot2_wind_rose/" data-toggle="tooltip" data-placement="top" title="Plot a wind rose in R">Next Post &rarr;</a>
          </li>
        
      </ul>


      
        
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:philmassie@webafrica.org.za" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/philmassie" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://twitter.com/philmassie" title="Twitter">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/philmassie" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.instagram.com/philmassie" title="Instagram">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
          <li>
            <a href="" title="RSS">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
        </ul>
        <p class="credits copyright text-muted">
          
            
              <a href="philmassie.github.io">Philip Massie</a>
            
          

          &nbsp;&bull;&nbsp;
          2017

          
            &nbsp;&bull;&nbsp;
            <a href="https://philmassie.github.io/">kabelsalat</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.31</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://philmassie.github.io/js/main.js"></script>
<script src="https://philmassie.github.io/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script><script> renderMathInElement(document.body); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js" integrity="sha256-UplRCs9v4KXVJvVY+p+RSo5Q4ilAUXh7kpjyIP5odyc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js" integrity="sha256-PWHOlUzc96pMc8ThwRIXPn8yH4NOLu42RQ0b9SpnpFk=" crossorigin="anonymous"></script>
<script src="https://philmassie.github.io/js/load-photoswipe.js"></script>



  </body>
</html>

